FROM bde2020/spark-maven-template:3.1.1-hadoop3.2

LABEL MAINTAINER="Gezim Sejdiu <g.sejdiu@gmail.com>"

ENV SPARK_APPLICATION_JAR_NAME Docker-Maven-Template-0.1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS eu.bde.template.maven.WordCount
ENV SPARK_APPLICATION_ARGS "/spark/README.md"