FROM bde2020/spark-base:3.1.1-hadoop3.2

LABEL maintainer="Gezim Sejdiu <g.sejdiu@gmail.com>, Giannis Mouchakis <gmouchakis@gmail.com>"

COPY history-server.sh /

EXPOSE 18081

CMD ["/bin/bash", "/history-server.sh"]
